# Ugesco : enrich and desambiguate the Samnang-Hans' JSON

In [10]:
from ugesco import *

Parse the json from Samnang and Hans. TODO : replace this temporary  jq parser with a pure Python script

%%cmd
jq -r ".[] | {beeldid, spatial : .spatial.value[]?, key : .spatial.key[]?, class1:.imageclassification.class1?, prob1:.imageclassification.prob1?, class2:.imageclassification.class2?, prob2:.imageclassification.prob2?} | [.beeldid, .spatial, .key, .class1, .prob1, .class2, .prob2] | @csv" data/jsondata_ugesco.json jq -r ".[] | {beeldid, spatial : .spatial.value[]?, key : .spatial.key[]?, class1:.imageclassification.class1?, prob1:.imageclassification.prob1?, class2:.imageclassification.class2?, prob2:.imageclassification.prob2?} | [.beeldid, .spatial, .key, .class1, .prob1, .class2, .prob2] | @csv" data/jsondata_ugesco.json > data/jsondata.csv

In [11]:
file = "data/jsondata_ugesco.json"
data = json_to_df(file)
data.columns

Index(['beeldid', 'imageclassification_class1', 'imageclassification_class2',
       'imageclassification_class3', 'imageclassification_class4',
       'imageclassification_class5', 'imageclassification_prob1',
       'imageclassification_prob2', 'imageclassification_prob3',
       'imageclassification_prob4', 'imageclassification_prob5', 'spatial',
       'spatial_key_0', 'spatial_key_1', 'spatial_key_2', 'spatial_key_3',
       'spatial_key_4', 'spatial_key_5', 'spatial_key_6', 'spatial_key_7',
       'spatial_value_0', 'spatial_value_1', 'spatial_value_2',
       'spatial_value_3', 'spatial_value_4', 'spatial_value_5',
       'spatial_value_6', 'spatial_value_7', 'temporal', 'temporal_key_0',
       'temporal_key_1', 'temporal_key_2', 'temporal_key_3', 'temporal_key_4',
       'temporal_value_0', 'temporal_value_1', 'temporal_value_2',
       'temporal_value_3', 'temporal_value_4'],
      dtype='object')

In [12]:
data.head(20)

,beeldid,imageclassification_class1,imageclassification_class2,imageclassification_class3,imageclassification_class4,imageclassification_class5,imageclassification_prob1,imageclassification_prob2,imageclassification_prob3,imageclassification_prob4,...,temporal_key_0,temporal_key_1,temporal_key_2,temporal_key_3,temporal_key_4,temporal_value_0,temporal_value_1,temporal_value_2,temporal_value_3,temporal_value_4
0,00009500,mosque/outdoor,synagogue/outdoor,church/outdoor,arch,palace,0.313512,0.242379,0.156034,0.062219,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,00009520,building_facade,hotel/outdoor,apartment_building/outdoor,office_building,palace,0.203420,0.184267,0.129882,0.071544,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,00009537,palace,mansion,castle,hospital,building_facade,0.334647,0.233139,0.180997,0.050541,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,00009544,library/outdoor,museum/outdoor,courtyard,courthouse,palace,0.706734,0.091893,0.028552,0.026621,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,00009549,street,promenade,ticket_booth,plaza,palace,0.554976,0.219579,0.063345,0.045276,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,00009551,plaza,embassy,hospital,mosque/outdoor,palace,0.184917,0.146900,0.138439,0.099211,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,00009705,church/outdoor,palace,tower,office_building,hospital,0.235078,0.206280,0.075990,0.068626,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,00009712,plaza,courthouse,cemetery,amusement_park,tower,0.151032,0.114809,0.113776,0.102538,...,TIMEX_DATE,NaN,NaN,NaN,NaN,Saint-Nicolas,NaN,NaN,NaN,NaN
8,00009732,street,plaza,courtyard,residential_neighborhood,alley,0.274491,0.186870,0.115429,0.102309,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,00009736,plaza,stage/outdoor,stage/indoor,music_studio,courthouse,0.147155,0.135074,0.070036,0.058131,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,00009746,church/outdoor,tower,palace,mosque/outdoor,mansion,0.212551,0.145003,0.133381,0.110916,...,TIMEX_DATE,NaN,NaN,NaN,NaN,3 mars 1942,NaN,NaN,NaN,NaN
11,00009764,church/outdoor,tower,plaza,palace,building_facade,0.642562,0.250606,0.033574,0.020762,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,00009770,mosque/outdoor,church/outdoor,tower,palace,building_facade,0.259349,0.248445,0.216372,0.079129,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,00009778,mosque/outdoor,tower,castle,church/outdoor,palace,0.243435,0.189359,0.099982,0.060488,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,00009848,crosswalk,parking_lot,staircase,skyscraper,office_building,0.271838,0.057216,0.031304,0.029158,...,TIMEX_DATE,NaN,NaN,NaN,NaN,18 juin 1815,NaN,NaN,NaN,NaN
15,00009967,plaza,embassy,palace,street,apartment_building/outdoor,0.405153,0.106920,0.083779,0.057322,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,00009971,plaza,museum/indoor,stage/indoor,schoolhouse,amusement_park,0.337939,0.152045,0.082777,0.059274,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,00010100,plaza,apartment_building/outdoor,courtyard,schoolhouse,office_building,0.223206,0.127881,0.099735,0.075835,...,TIMEX_TIME,NaN,NaN,NaN,NaN,lundi de Pâques,NaN,NaN,NaN,NaN
18,00010106,church/outdoor,campus,plaza,tower,schoolhouse,0.130993,0.124749,0.105384,0.102687,...,TIMEX_TIME,NaN,NaN,NaN,NaN,lundi de Pâques,NaN,NaN,NaN,NaN
19,00010116,church/outdoor,courthouse,tower,schoolhouse,plaza,0.674401,0.069765,0.059246,0.030000,...,TIMEX_TIME,NaN,NaN,NaN,NaN,lundi de Pâques,NaN,NaN,NaN,NaN

In [13]:
#Drop temporal columns
to_drop = [c for c in data.columns if c.startswith('temporal')]
data.drop(to_drop, axis=1, inplace=True)
data.head()

,beeldid,imageclassification_class1,imageclassification_class2,imageclassification_class3,imageclassification_class4,imageclassification_class5,imageclassification_prob1,imageclassification_prob2,imageclassification_prob3,imageclassification_prob4,...,spatial_key_6,spatial_key_7,spatial_value_0,spatial_value_1,spatial_value_2,spatial_value_3,spatial_value_4,spatial_value_5,spatial_value_6,spatial_value_7
0,00009500,mosque/outdoor,synagogue/outdoor,church/outdoor,arch,palace,0.313512,0.242379,0.156034,0.062219,...,NaN,NaN,Brussel,L' église St . e. Marie,NaN,NaN,NaN,NaN,NaN,NaN
1,00009520,building_facade,hotel/outdoor,apartment_building/outdoor,office_building,palace,0.203420,0.184267,0.129882,0.071544,...,NaN,NaN,Bruxelles,Grand ' Place,NaN,NaN,NaN,NaN,NaN,NaN
2,00009537,palace,mansion,castle,hospital,building_facade,0.334647,0.233139,0.180997,0.050541,...,NaN,NaN,Bruxelles,La Château de Tervuren,NaN,NaN,NaN,NaN,NaN,NaN
3,00009544,library/outdoor,museum/outdoor,courtyard,courthouse,palace,0.706734,0.091893,0.028552,0.026621,...,NaN,NaN,Bruxelles,Place de la Monnaie,NaN,NaN,NaN,NaN,NaN,NaN
4,00009549,street,promenade,ticket_booth,plaza,palace,0.554976,0.219579,0.063345,0.045276,...,NaN,NaN,Bruxelles,Palais de Justice,rue Royale,NaN,NaN,NaN,NaN,NaN

In [15]:
#remove class and prob 3 to 5
data.drop(list(data.filter(regex = '(_class|_prob)[3-5]$')), axis = 1, inplace = True)

In [16]:
#Delete "indoor", "outdoor" etc in class names and replace undescores with spaces
data['imageclassification_class1'] = data['imageclassification_class1'].str.replace("/.+", "").str.replace('_', ' ')
data['imageclassification_class2'] = data['imageclassification_class2'].str.replace("/.+", "").str.replace('_', ' ')
data.head()

,beeldid,imageclassification_class1,imageclassification_class2,imageclassification_prob1,imageclassification_prob2,spatial,spatial_key_0,spatial_key_1,spatial_key_2,spatial_key_3,...,spatial_key_6,spatial_key_7,spatial_value_0,spatial_value_1,spatial_value_2,spatial_value_3,spatial_value_4,spatial_value_5,spatial_value_6,spatial_value_7
0,00009500,mosque,synagogue,0.313512,0.242379,NaN,LOC_PLACE,LOC_BUILDING,NaN,NaN,...,NaN,NaN,Brussel,L' église St . e. Marie,NaN,NaN,NaN,NaN,NaN,NaN
1,00009520,building facade,hotel,0.203420,0.184267,NaN,LOC_PLACE,LOC_STREET,NaN,NaN,...,NaN,NaN,Bruxelles,Grand ' Place,NaN,NaN,NaN,NaN,NaN,NaN
2,00009537,palace,mansion,0.334647,0.233139,NaN,LOC_PLACE,LOC_BUILDING,NaN,NaN,...,NaN,NaN,Bruxelles,La Château de Tervuren,NaN,NaN,NaN,NaN,NaN,NaN
3,00009544,library,museum,0.706734,0.091893,NaN,LOC_PLACE,LOC_SPACES,NaN,NaN,...,NaN,NaN,Bruxelles,Place de la Monnaie,NaN,NaN,NaN,NaN,NaN,NaN
4,00009549,street,promenade,0.554976,0.219579,NaN,LOC_PLACE,LOC_BUILDING,LOC_STREET,NaN,...,NaN,NaN,Bruxelles,Palais de Justice,rue Royale,NaN,NaN,NaN,NaN,NaN

In [17]:
class_places = pd.read_csv("data/classes_places.csv", encoding="utf8")
class_places.head()

,original_class,class,class_id,subclass of,precision,getty_link,AAT_subject_id,AAT_preffered_terms
0,archive,archive,Q166118,GLAM,NaN,http://vocabsservices.getty.edu/AATService.asm...,300124822.0,archives (buildings)
1,NaN,NaN,NaN,cultural institution,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,historical source,NaN,NaN,NaN,NaN
3,ice shelf,ice shelf,Q46966,glacier,NaN,http://vocabsservices.getty.edu/AATService.asm...,NaN,NaN
4,cemetery,cemetery,Q39614,terrain,NaN,http://vocabsservices.getty.edu/AATService.asm...,300266755.0,cemeteries

In [19]:
# join/merge with classes_places.csv to get the class_ids
data = pd.merge(data, class_places, how='left', left_on=['imageclassification_class1'], right_on=['original_class'])
data = data.rename(columns={'class_id': 'class_id1'})

In [20]:
data = pd.merge(data, class_places, how='left', left_on=['imageclassification_class2'], right_on=['original_class'], suffixes=['', '_x'])
data = data.rename(columns={'class_id': 'class_id2'})

In [25]:
to_drop = [c for c in data.columns if c.endswith('_x') or c.endswith('_y') or c.startswith('AAT')]
data.drop(to_drop, axis=1, inplace=True)
data.head()

,beeldid,imageclassification_class1,imageclassification_class2,imageclassification_prob1,imageclassification_prob2,spatial,spatial_key_0,spatial_key_1,spatial_key_2,spatial_key_3,...,spatial_value_6,spatial_value_7,class_id1,class_id1,original_class,class,class_id2,subclass of,precision,getty_link
0,00009500,mosque,synagogue,0.313512,0.242379,NaN,LOC_PLACE,LOC_BUILDING,NaN,NaN,...,NaN,NaN,Q32815,Q32815,synagogue,synagogue,Q34627,temple,outdoor,http://vocabsservices.getty.edu/AATService.asm...
1,00009520,building facade,hotel,0.203420,0.184267,NaN,LOC_PLACE,LOC_STREET,NaN,NaN,...,NaN,NaN,Q41176,Q41176,hotel,hotel,Q27686,commercial building,outdoor,http://vocabsservices.getty.edu/AATService.asm...
2,00009537,palace,mansion,0.334647,0.233139,NaN,LOC_PLACE,LOC_BUILDING,NaN,NaN,...,NaN,NaN,Q16560,Q16560,mansion,mansion,Q1802963,house,NaN,http://vocabsservices.getty.edu/AATService.asm...
3,00009544,library,museum,0.706734,0.091893,NaN,LOC_PLACE,LOC_SPACES,NaN,NaN,...,NaN,NaN,Q856584,Q856584,museum,museum building,Q24699794,public building,indoor,http://vocabsservices.getty.edu/AATService.asm...
4,00009544,library,museum,0.706734,0.091893,NaN,LOC_PLACE,LOC_SPACES,NaN,NaN,...,NaN,NaN,Q856584,Q856584,museum,museum building,Q24699794,public building,outdoor,http://vocabsservices.getty.edu/AATService.asm...

In [26]:
#join/merge with pallas_photothèque to get the keywords
phototeque = pd.read_csv("data/phototheque_pallas.csv", encoding="utf8", dtype={'beeldid': str})
#phototeque.head()
data = pd.merge(data, phototeque, how='left', on=['beeldid'], suffixes=['', '_x'])
data.head()

,beeldid,imageclassification_class1,imageclassification_class2,imageclassification_prob1,imageclassification_prob2,spatial,spatial_key_0,spatial_key_1,spatial_key_2,spatial_key_3,...,class_id1,original_class,class,class_id2,subclass of,precision,getty_link,LEGEND,BPALLASF,keywords_fr
0,00009500,mosque,synagogue,0.313512,0.242379,NaN,LOC_PLACE,LOC_BUILDING,NaN,NaN,...,Q32815,synagogue,synagogue,Q34627,temple,outdoor,http://vocabsservices.getty.edu/AATService.asm...,Brussel. L'église St.e. Marie. [Sipho],Vues de Bruxelles : 1942-1944. - 124 photos,bruxelles (belgique)--photographies
1,00009500,mosque,synagogue,0.313512,0.242379,NaN,LOC_PLACE,LOC_BUILDING,NaN,NaN,...,Q32815,synagogue,synagogue,Q34627,temple,outdoor,http://vocabsservices.getty.edu/AATService.asm...,NaN,NaN,"ehrhardt, alfred (1901-1984)"
2,00009500,mosque,synagogue,0.313512,0.242379,NaN,LOC_PLACE,LOC_BUILDING,NaN,NaN,...,Q32815,synagogue,synagogue,Q34627,temple,outdoor,http://vocabsservices.getty.edu/AATService.asm...,NaN,NaN,"armstrong, bob"
3,00009500,mosque,synagogue,0.313512,0.242379,NaN,LOC_PLACE,LOC_BUILDING,NaN,NaN,...,Q32815,synagogue,synagogue,Q34627,temple,outdoor,http://vocabsservices.getty.edu/AATService.asm...,NaN,NaN,miessen
4,00009500,mosque,synagogue,0.313512,0.242379,NaN,LOC_PLACE,LOC_BUILDING,NaN,NaN,...,Q32815,synagogue,synagogue,Q34627,temple,outdoor,http://vocabsservices.getty.edu/AATService.asm...,NaN,NaN,"churchill, winston (1874-1965)"

In [ ]:
#filter rows with null value
#data[data['LEGEND'].isnull()]

In [27]:
#join/merge with pallas_motcles_lieux_complet.csv to get the locations in the keywords
mots_cles = pd.read_csv("data/pallas_motcles_lieux_complet.csv", encoding="utf8")
#mots_cles.head()
data = pd.merge(data, mots_cles, how='left', left_on=['keywords_fr'], right_on=['keyword'], suffixes=['', '_x'])
data.head()

,beeldid,imageclassification_class1,imageclassification_class2,imageclassification_prob1,imageclassification_prob2,spatial,spatial_key_0,spatial_key_1,spatial_key_2,spatial_key_3,...,LEGEND,BPALLASF,keywords_fr,File,trfwnumm,keyword,country_name,country_qid,loc_name,loc_qid
0,00009500,mosque,synagogue,0.313512,0.242379,NaN,LOC_PLACE,LOC_BUILDING,NaN,NaN,...,Brussel. L'église St.e. Marie. [Sipho],Vues de Bruxelles : 1942-1944. - 124 photos,bruxelles (belgique)--photographies,pallas_motcles_lieux.csv,214,bruxelles (belgique)--photographies,Belgique,Q31,Bruxelles,Q239
1,00009500,mosque,synagogue,0.313512,0.242379,NaN,LOC_PLACE,LOC_BUILDING,NaN,NaN,...,NaN,NaN,"ehrhardt, alfred (1901-1984)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,00009500,mosque,synagogue,0.313512,0.242379,NaN,LOC_PLACE,LOC_BUILDING,NaN,NaN,...,NaN,NaN,"armstrong, bob",NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,00009500,mosque,synagogue,0.313512,0.242379,NaN,LOC_PLACE,LOC_BUILDING,NaN,NaN,...,NaN,NaN,miessen,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,00009500,mosque,synagogue,0.313512,0.242379,NaN,LOC_PLACE,LOC_BUILDING,NaN,NaN,...,NaN,NaN,"churchill, winston (1874-1965)",NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
#filter rows with non null value in loc_name
locs = data[data['loc_name'].notnull()]
locs.shape

(1582, 40)

In [29]:
locs.head(20)

,beeldid,imageclassification_class1,imageclassification_class2,imageclassification_prob1,imageclassification_prob2,spatial,spatial_key_0,spatial_key_1,spatial_key_2,spatial_key_3,...,LEGEND,BPALLASF,keywords_fr,File,trfwnumm,keyword,country_name,country_qid,loc_name,loc_qid
0,00009500,mosque,synagogue,0.313512,0.242379,NaN,LOC_PLACE,LOC_BUILDING,NaN,NaN,...,Brussel. L'église St.e. Marie. [Sipho],Vues de Bruxelles : 1942-1944. - 124 photos,bruxelles (belgique)--photographies,pallas_motcles_lieux.csv,214,bruxelles (belgique)--photographies,Belgique,Q31,Bruxelles,Q239
15,00009520,building facade,hotel,0.203420,0.184267,NaN,LOC_PLACE,LOC_STREET,NaN,NaN,...,Bruxelles. Grand' Place.,Vues de Bruxelles : 1942-1944. - 124 photos,bruxelles (belgique)--photographies,pallas_motcles_lieux.csv,214,bruxelles (belgique)--photographies,Belgique,Q31,Bruxelles,Q239
30,00009537,palace,mansion,0.334647,0.233139,NaN,LOC_PLACE,LOC_BUILDING,NaN,NaN,...,Bruxelles. La Château de Tervuren. [Sipho],Vues de Bruxelles : 1942-1944. - 124 photos,bruxelles (belgique)--photographies,pallas_motcles_lieux.csv,214,bruxelles (belgique)--photographies,Belgique,Q31,Bruxelles,Q239
45,00009544,library,museum,0.706734,0.091893,NaN,LOC_PLACE,LOC_SPACES,NaN,NaN,...,Bruxelles. Place de la Monnaie. [Sipho],Vues de Bruxelles : 1942-1944. - 124 photos,bruxelles (belgique)--photographies,pallas_motcles_lieux.csv,214,bruxelles (belgique)--photographies,Belgique,Q31,Bruxelles,Q239
60,00009544,library,museum,0.706734,0.091893,NaN,LOC_PLACE,LOC_SPACES,NaN,NaN,...,Bruxelles. Place de la Monnaie. [Sipho],Vues de Bruxelles : 1942-1944. - 124 photos,bruxelles (belgique)--photographies,pallas_motcles_lieux.csv,214,bruxelles (belgique)--photographies,Belgique,Q31,Bruxelles,Q239
75,00009544,library,museum,0.706734,0.091893,NaN,LOC_PLACE,LOC_SPACES,NaN,NaN,...,Bruxelles. Place de la Monnaie. [Sipho],Vues de Bruxelles : 1942-1944. - 124 photos,bruxelles (belgique)--photographies,pallas_motcles_lieux.csv,214,bruxelles (belgique)--photographies,Belgique,Q31,Bruxelles,Q239
90,00009544,library,museum,0.706734,0.091893,NaN,LOC_PLACE,LOC_SPACES,NaN,NaN,...,Bruxelles. Place de la Monnaie. [Sipho],Vues de Bruxelles : 1942-1944. - 124 photos,bruxelles (belgique)--photographies,pallas_motcles_lieux.csv,214,bruxelles (belgique)--photographies,Belgique,Q31,Bruxelles,Q239
105,00009544,library,museum,0.706734,0.091893,NaN,LOC_PLACE,LOC_SPACES,NaN,NaN,...,Bruxelles. Place de la Monnaie. [Sipho],Vues de Bruxelles : 1942-1944. - 124 photos,bruxelles (belgique)--photographies,pallas_motcles_lieux.csv,214,bruxelles (belgique)--photographies,Belgique,Q31,Bruxelles,Q239
120,00009544,library,museum,0.706734,0.091893,NaN,LOC_PLACE,LOC_SPACES,NaN,NaN,...,Bruxelles. Place de la Monnaie. [Sipho],Vues de Bruxelles : 1942-1944. - 124 photos,bruxelles (belgique)--photographies,pallas_motcles_lieux.csv,214,bruxelles (belgique)--photographies,Belgique,Q31,Bruxelles,Q239
135,00009544,library,museum,0.706734,0.091893,NaN,LOC_PLACE,LOC_SPACES,NaN,NaN,...,Bruxelles. Place de la Monnaie. [Sipho],Vues de Bruxelles : 1942-1944. - 124 photos,bruxelles (belgique)--photographies,pallas_motcles_lieux.csv,214,bruxelles (belgique)--photographies,Belgique,Q31,Bruxelles,Q239
150,00009544,library,museum,0.706734,0.091893,NaN,LOC_PLACE,LOC_SPACES,NaN,NaN,...,Bruxelles. Place de la Monnaie. [Sipho],Vues de Bruxelles : 1942-1944. - 124 photos,bruxelles (belgique)--photographies,pallas_motcles_lieux.csv,214,bruxelles (belgique)--photographies,Belgique,Q31,Bruxelles,Q239
165,00009549,street,promenade,0.554976,0.219579,NaN,LOC_PLACE,LOC_BUILDING,LOC_STREET,NaN,...,Bruxelles. Vue du Palais de Justice pris du Pa...,Vues de Bruxelles : 1942-1944. - 124 photos,bruxelles (belgique)--photographies,pallas_motcles_lieux.csv,214,bruxelles (belgique)--photographies,Belgique,Q31,Bruxelles,Q239
180,00009551,plaza,embassy,0.184917,0.146900,NaN,LOC_PLACE,LOC_BUILDING,NaN,NaN,...,Bruxelles - La gare du Nord. [Sipho],Vues de Bruxelles : 1942-1944. - 124 photos,bruxelles (belgique)--photographies,pallas_motcles_lieux.csv,214,bruxelles (belgique)--photographies,Belgique,Q31,Bruxelles,Q239
195,00009705,church,palace,0.235078,0.206280,NaN,LOC_PLACE,NaN,NaN,NaN,...,Gand. Hôtel des Postes. [Frei gegeben durch ze...,"Vues de Gent, 1942-1943. - 54 photos",gent (belgique)--photographies,pallas_motcles_lieux.csv,246,gent (belgique)--photographies,Belgique,Q31,Gand,Q1296
199,00009705,church,palace,0.235078,0.206280,NaN,LOC_PLACE,NaN,NaN,NaN,...,Gand. Hôtel des Postes. [Frei gegeben durch ze...,"Vues de Gent, 1942-1943. - 54 photos",gent (belgique)--photographies,pallas_motcles_lieux.csv,246,gent (belgique)--photographies,Belgique,Q31,Gand,Q1296
203,00009705,church,palace,0.235078,0.206280,NaN,LOC_PLACE,NaN,NaN,NaN,...,Gand. Hôtel des Postes. [Frei gegeben durch ze...,"Vues de Gent, 1942-1943. - 54 photos",gent (belgique)--photographies,pallas_motcles_lieux.csv,246,gent (belgique)--photographies,Belgique,Q31,Gand,Q1296
207,00009705,church,palace,0.235078,0.206280,NaN,LOC_PLACE,NaN,NaN,NaN,...,Gand. Hôtel des Postes. [Frei gegeben durch ze...,"Vues de Gent, 1942-1943. - 54 photos",gent (belgique)--photographies,pallas_motcles_lieux.csv,246,gent (belgique)--photographies,Belgique,Q31,Gand,Q1296
212,00009712,plaza,courthouse,0.151032,0.114809,NaN,LOC_BUILDING,NaN,NaN,NaN,...,NaN,NaN,gent (belgique)--photographies,pallas_motcles_lieux.csv,246,gent (belgique)--photographies,Belgique,Q31,Gand,Q1296
215,00009732,street,plaza,0.274491,0.186870,NaN,LOC_PLACE,NaN,NaN,NaN,...,Gand. Maison des Bouchers. [Sipho],"Vues de Gent, 1942-1943. - 54 photos",gent (belgique)--photographies,pallas_motcles_lieux.csv,246,gent (belgique)--photographies,Belgique,Q31,Gand,Q1296
219,00009736,plaza,stage,0.147155,0.135074,NaN,LOC_PLACE,LOC_MONUMENT,LOC_PLACE,NaN,...,"Gand, 4e Ville du Royaume est à la fois une vi...","Vues de Gent, 1942-1943. - 54 photos",gent (belgique)--photographies,pallas_motcles_lieux.csv,246,gent (belgique)--photographies,Belgique,Q31,Gand,Q1296

In [30]:
locs.to_csv("C:/Users/ettor/Desktop/test.csv")